version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: joe
  coins:
  - 10000token
- name: storage
  address: cosmos1nt2864p8390qm6tctx33e3zt8gh6aehpqv089g
  coins:
  - "10token"
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
